// Icon mapping to avoid importing entire react-icons library
// This reduces bundle size from 5MB+ to ~200KB
import {
  SiReact,
  SiNextdotjs,
  SiNodedotjs,
  SiExpress,
  SiLaravel,
  SiDotnet,
  SiMysql,
  SiSupabase,
  SiFirebase,
  SiStrapi,
  SiJavascript,
  SiTailwindcss,
  SiAngular,
  SiBootstrap,
  SiMaterialdesign,
  SiFlutter,
  SiDart,
  SiAndroidstudio,
  SiKotlin,
  SiGit,
  SiGithub,
  SiHtml5,
  SiCss3,
  SiFigma,
  SiAdobephotoshop,
  SiDigitalocean,
  SiDocker,
} from 'react-icons/si';
import { MdOutlineCheckCircle, MdOutlineBugReport, MdOutlineDevices, MdOutlineEditNote } from 'react-icons/md';

export const iconMap = {
  SiReact,
  SiNextdotjs,
  SiNodedotjs,
  SiExpress,
  SiLaravel,
  SiDotnet,
  SiMysql,
  SiSupabase,
  SiFirebase,
  SiStrapi,
  SiJavascript,
  SiTailwindcss,
  SiAngular,
  SiBootstrap,
  SiMaterialdesign,
  SiFlutter,
  SiDart,
  SiAndroidstudio,
  SiKotlin,
  SiGit,
  SiGithub,
  SiHtml5,
  SiCss3,
  SiFigma,
  SiAdobephotoshop,
  SiDigitalocean,
  SiDocker,
  MdOutlineCheckCircle,
  MdOutlineBugReport,
  MdOutlineDevices,
  MdOutlineEditNote,
};
