// Icon mapping to avoid importing entire react-icons library
// This reduces bundle size from 5MB+ to ~200KB
import {
  SiReact,
  SiNodedotjs,
  SiExpress,
  SiLaravel,
  SiDotnet,
  SiMysql,
  SiJavascript,
  SiTailwindcss,
  SiAngular,
  SiBootstrap,
  SiMaterialdesign,
  SiAndroidstudio,
  SiKotlin,
  SiGit,
  SiGithub,
  SiHtml5,
  SiCss3,
  SiFigma,
  SiAdobephotoshop,
} from 'react-icons/si';

export const iconMap = {
  SiReact,
  SiNodedotjs,
  SiExpress,
  SiLaravel,
  SiDotnet,
  SiMysql,
  SiJavascript,
  SiTailwindcss,
  SiAngular,
  SiBootstrap,
  SiMaterialdesign,
  SiAndroidstudio,
  SiKotlin,
  SiGit,
  SiGithub,
  SiHtml5,
  SiCss3,
  SiFigma,
  SiAdobephotoshop,
};
